### ISSUE TITLE
Datenbank (NoSQL (Mongo))

### ISSUE THREAD

**Issue by maxleonalbrecht** [darfichraus-de/api#5]
- Aufsatz einer Mongo DB
- Stefan hat die Datenbank aufgesetzt
- Stefan verwaltet den Zugang zu der Datenbank

**Comment by stefanmichalk** [comment]
**Host** db.darfichraus.de (Default-Port Mongo: 27017)
**User** darfichraus
**Pass** 9iecMnHFWpU7LjkFF4gu
